# Generated by Django 5.1 on 2024-08-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimStudents',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimSubjects',
            fields=[
                ('subject_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FactScores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer_score.dimstudents')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer_score.dimsubjects')),
            ],
        ),
    ]
