# Generated by Django 5.1 on 2024-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0002_alter_dimstudents_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factscores',
            name='subject',
            field=models.CharField(max_length=8),
        ),
    ]
