# Generated by Django 5.1 on 2024-08-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0003_alter_factscores_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factscores',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='factscores',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
