# Generated by Django 5.1 on 2024-08-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0004_rename_student_factscores_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimstudents',
            old_name='student_id',
            new_name='student',
        ),
    ]
