# Generated by Django 5.1 on 2024-08-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0005_rename_student_id_dimstudents_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimstudents',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='factscores',
            old_name='student_id',
            new_name='student',
        ),
    ]
