# Generated by Django 5.1 on 2024-08-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0006_rename_student_dimstudents_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factscores',
            old_name='student',
            new_name='student_id',
        ),
    ]
