# Generated by Django 5.1 on 2024-08-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0007_rename_student_factscores_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factscores',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='factscores',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='factscores',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Analyzer_score.dimsubjects'),
            preserve_default=False,
        ),
    ]
