# Generated by Django 5.1 on 2024-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer_score', '0008_rename_student_id_factscores_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factscores',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='factscores',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.AddConstraint(
            model_name='factscores',
            constraint=models.UniqueConstraint(fields=('student_id', 'subject_id'), name='unique_student_subject'),
        ),
    ]
